meta_product_name: "medlii"
meta_title: "medlii - From professionals to casuals, find your music partner"
meta_description: "Find your music partner in just a few seconds"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@medlii_app"   # required for Twitter Cards
