

meta_product_name: "medlii"
meta_title: "medlii - From professionals to casuals, find your music partner"
meta_description: "Find a music partner nearby and start playing"
meta_image: "medlii_cover.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@medlii_app"   # required for Twitter Cards
